### ISSUE TITLE
Build failure on musl since version 10.0

### ISSUE THREAD

**Issue by ffontaine** [apitrace/apitrace#755]
Build on musl is broken since version 10.0 because the include on `config.h` was removed from `backtrace.h` by https://github.com/apitrace/apitrace/commit/1544abf59d68d74977b8b692bea4d7468d65547b:

```
In file included from /home/buildroot/autobuild/instance-3/output-1/build/apitrace-10.0/thirdparty/libbacktrace/testlib.c:40:
/home/buildroot/autobuild/instance-3/output-1/build/apitrace-10.0/thirdparty/libbacktrace/backtrace.h:53:10: fatal error: gstdint.h: No such file or directory
   53 | #include "gstdint.h"
      |          ^~~~~~~~~~~
```

Full build log:
 - http://autobuild.buildroot.org/results/a10793d01efa3a1533ba37aa845b9ac2bb1dfb6b

I'll not send a PR as it should not affect master because of https://github.com/apitrace/apitrace/commit/b1c99dbdb93171a1aa4359bc7c9e201d395a0058

**Comment by jrfonseca** [comment]
It's not clear if this was this was a transitory upstream bug? Or a mistake due to hand merging  of 1544abf59d68d74977b8b692bea4d7468d65547b?

Either way, I'd rather not maintaining stable point releases, which cherry-picked changes.  What I can do is release another major release in the near future.  It's less work.

**Comment by ffontaine** [comment]
Do you still plan to release a new major release?

**Comment by jrfonseca** [comment]
Done.  Sorry
